class_names:
- member1
- member2
- member3
input_shape:
- 224
- 224
- 3
model_type: custom
num_classes: 3
performance:
  best_val_accuracy: 1.0
  best_val_loss: 0.12922747433185577
  test_accuracy: 1.0
  test_loss: 0.12922747433185577
total_parameters: 28643
trainable_parameters: 28291
training_config:
  batch_size: 16
  best_epoch: 20
  epochs_trained: 35
  learning_rate: 0.0001
  loss: categorical_crossentropy
  optimizer: adam
training_data:
  num_test_samples: 220
  num_train_samples: 878
  num_val_samples: 220
